version: '3.8'

services:
  fastapi:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      - PYTHON_ENV=production
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/predator_db
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_URL=http://qdrant:6333
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minio_access_key
      - MINIO_SECRET_KEY=minio_secret_key
    depends_on:
      - postgres
      - redis
      - qdrant
      - minio
    volumes:
      - ./fastapi_app:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=predator_db
    volumes:
      - ../../databases/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    volumes:
      - ../../databases/redis/data:/data
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - ../../databases/qdrant/data:/qdrant/storage
    ports:
      - "6333:6333"

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=minio_access_key
      - MINIO_ROOT_PASSWORD=minio_secret_key
    volumes:
      - ../../databases/minio/data:/data
    ports:
      - "9000:9000"
    command: server /data 