apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: predator-build-test-release
spec:
  params:
    - name: image
    - name: commit
  tasks:
    - name: build
      taskRef: { name: kaniko-build }
      params: [{ name: image, value: "$(params.image)" }]
    - name: test
      runAfter: [build]
      taskRef: { name: pytest }
    - name: scan
      runAfter: [build]
      taskRef: { name: trivy-scan }
    - name: release
      runAfter: [test, scan]
      taskRef: { name: release-tag }
      params: [{ name: commit, value: "$(params.commit)" }]
    - name: update-manifests
      runAfter: [release]
      taskRef: { name: manifests-bump-and-seal }
    - name: argocd-sync
      runAfter: [update-manifests]
      taskRef: { name: argocd-sync-wait }
