#!/usr/bin/env python3
"""MetaSupervisorAgent (MVP)

Lightweight autonomous scanner and reporter for Predator Analytics.
Runs periodic scans (files, git last commit, kubernetes pods via kubectl if present,
Prometheus query if PROMETHEUS_URL provided) and writes:
 - analytics/autogenerated_tech_spec.md
 - logs/meta_supervisor.log
 - data/meta/system_health.json

Designed to run locally or in a container as a Cron/Deployment.
Configuration via environment variables.
"""
from __future__ import annotations

import json
import logging
import os
import subprocess
import sys
import time
from datetime import datetime
from typing import Any, Dict, List, Optional

import requests

ROOT_PATHS = os.getenv("META_ROOT_PATHS", "backend,agents,helm,observability").split(",")
SCAN_INTERVAL = int(os.getenv("META_SCAN_INTERVAL", "300"))  # seconds
PROMETHEUS_URL = os.getenv("PROMETHEUS_URL", "http://localhost:9090")

OUT_SPEC = os.getenv("META_SPEC_PATH", "analytics/autogenerated_tech_spec.md")
OUT_LOG = os.getenv("META_LOG_PATH", "logs/meta_supervisor.log")
OUT_JSON = os.getenv("META_HEALTH_JSON", "data/meta/system_health.json")

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    handlers=[logging.FileHandler(OUT_LOG), logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger("meta-supervisor")


def run_cmd(cmd: List[str], timeout: int = 10) -> Optional[str]:
    try:
        res = subprocess.run(
            cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True, timeout=timeout
        )
        return res.stdout.decode().strip()
    except Exception as e:
        logger.debug("Command %s failed: %s", cmd, e)
        return None


def git_last_commit() -> Dict[str, Any]:
    out = run_cmd(["git", "log", "-n", "1", "--pretty=format:%H|%an|%ad|%s"])
    if not out:
        return {}
    parts = out.split("|", 3)
    return {"hash": parts[0], "author": parts[1], "date": parts[2], "message": parts[3]}


def git_recent_changed_files(n_commits: int = 5) -> List[str]:
    out = run_cmd(["git", "diff", f"HEAD~{n_commits}", "--name-only"]) or ""
    files = [l for l in out.splitlines() if l]
    return files


def scan_files(paths: List[str]) -> Dict[str, Any]:
    files_info = {}
    for p in paths:
        p = p.strip()
        if not os.path.exists(p):
            continue
        count = 0
        latest_mtime = 0.0
        for dirpath, dirnames, filenames in os.walk(p):
            for fn in filenames:
                count += 1
                try:
                    m = os.path.getmtime(os.path.join(dirpath, fn))
                    if m > latest_mtime:
                        latest_mtime = m
                except Exception:
                    continue
        files_info[p] = {
            "count": count,
            "latest_mtime": (
                datetime.utcfromtimestamp(latest_mtime).isoformat() if latest_mtime else None
            ),
        }
    return files_info


def query_prometheus(query: str = "up") -> Dict[str, Any]:
    if not PROMETHEUS_URL:
        return {}
    url = PROMETHEUS_URL.rstrip("/") + "/api/v1/query"
    try:
        r = requests.get(url, params={"query": query}, timeout=5)
        r.raise_for_status()
        return r.json()
    except Exception as e:
        logger.debug("Prometheus query failed: %s", e)
        return {"error": str(e)}


def kubectl_get_pods() -> Dict[str, Any]:
    out = run_cmd(["kubectl", "get", "pods", "--all-namespaces", "-o", "json"], timeout=10)
    if not out:
        return {"error": "kubectl not available or failed"}
    try:
        return json.loads(out)
    except Exception as e:
        logger.debug("kubectl output parse error: %s", e)
        return {"error": "parse_error"}


def build_health_report() -> Dict[str, Any]:
    logger.info("Building health report")
    report: Dict[str, Any] = {"timestamp": datetime.utcnow().isoformat(), "scans": {}}
    report["scans"]["files"] = scan_files(ROOT_PATHS)
    report["scans"]["git_last_commit"] = git_last_commit()
    report["scans"]["recent_changed_files"] = git_recent_changed_files()
    report["scans"]["prometheus_up"] = query_prometheus("up")
    report["scans"]["k8s_pods"] = kubectl_get_pods()
    return report


def render_spec(report: Dict[str, Any]) -> str:
    lines: List[str] = []
    lines.append("# Autogenerated Tech Spec — MetaSupervisorAgent\n")
    lines.append(f"Generated: {report.get('timestamp')} UTC\n")

    # Current goals (placeholder)
    lines.append("## Current goals\n")
    lines.append(
        "- Maintain service health and detect regressions\n- Auto-generate remediation tasks when safe\n"
    )

    # Detected divergences
    lines.append("## Detected divergences / findings\n")
    gitc = report.get("scans", {}).get("git_last_commit", {})
    if gitc:
        lines.append(
            f"- Last commit: {gitc.get('hash')} by {gitc.get('author')} on {gitc.get('date')}: {gitc.get('message')}\n"
        )
    changed = report.get("scans", {}).get("recent_changed_files", [])
    if changed:
        lines.append("- Recently changed files (from git):\n")
        for f in changed[:50]:
            lines.append(f"  - {f}\n")
    else:
        lines.append("- No recent changed files detected in git range.\n")

    lines.append("\n## Suggested actions\n")
    # Simple heuristic examples
    prometheus_up = report.get("scans", {}).get("prometheus_up", {})
    if prometheus_up.get("status") == "success":
        up_data = prometheus_up.get("data", {}).get("result", [])
        down = [
            r for r in up_data if r.get("metric", {}).get("job") and r.get("value", [])[1] == "0"
        ]
        if down:
            lines.append(
                f"- Found {len(down)} targets reporting down in Prometheus. Recommend investigating scrape targets.\n"
            )
    else:
        lines.append("- Could not query Prometheus; check PROMETHEUS_URL and network.\n")

    # K8s hints
    pods = report.get("scans", {}).get("k8s_pods", {})
    if pods and isinstance(pods, dict) and pods.get("items"):
        crashing = [
            p
            for p in pods.get("items", [])
            if any(
                cs.get("restartCount", 0) > 0
                for cs in (p.get("status", {}).get("containerStatuses") or [])
            )
        ]
        if crashing:
            lines.append(
                f"- {len(crashing)} pods have restarts; consider inspecting container logs and readiness probes.\n"
            )

    lines.append("\n## Actions taken (auto-history)\n")
    # append existing history if present
    if os.path.exists(OUT_SPEC):
        try:
            with open(OUT_SPEC, "r", encoding="utf-8") as f:
                f.read()
            lines.append("(previous spec present — preserved in archived copies)\n")
        except Exception:
            pass

    return "\n".join(lines)


def write_outputs(report: Dict[str, Any]) -> None:
    # ensure dirs
    os.makedirs(os.path.dirname(OUT_SPEC) or ".", exist_ok=True)
    os.makedirs(os.path.dirname(OUT_JSON) or ".", exist_ok=True)
    os.makedirs(os.path.dirname(OUT_LOG) or ".", exist_ok=True)

    spec = render_spec(report)
    with open(OUT_SPEC, "w", encoding="utf-8") as f:
        f.write(spec)
    with open(OUT_JSON, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)

    logger.info("Wrote spec to %s, health json to %s", OUT_SPEC, OUT_JSON)


def main_loop():
    logger.info("Starting MetaSupervisorAgent (interval=%s s)", SCAN_INTERVAL)
    while True:
        try:
            report = build_health_report()
            write_outputs(report)
        except Exception as e:
            logger.exception("MetaSupervisor run failed: %s", e)
        time.sleep(SCAN_INTERVAL)


if __name__ == "__main__":
    # Allow a single-run mode for CI/test
    if "--once" in sys.argv:
        r = build_health_report()
        write_outputs(r)
        print("Done (once)")
        sys.exit(0)
    main_loop()
