server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchwait: 1s
    batchsize: 1024000
    timeout: 10s

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log
          host: ${HOSTNAME}

  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: container_logs
          __path__: /var/lib/docker/containers/*/*.log
          host: ${HOSTNAME}
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            container_name: attrs.container.name
            pod_name: attrs.pod.name
            namespace: attrs.pod.namespace
      - labels:
          stream:
          container_name:
          pod_name:
          namespace:
      - output:
          source: log

  - job_name: journal
    journal:
      max_age: 12h
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: 'hostname'
