global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'predator11'
    environment: 'development'

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  # Predator11 Backend API
  - job_name: 'predator11-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: /metrics
    scrape_interval: 15s

  # Keycloak
  - job_name: 'keycloak'
    static_configs:
      - targets: ['keycloak:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  # OpenSearch Exporter
  - job_name: 'opensearch-exporter'
    static_configs:
      - targets: ['opensearch-exporter:9114']
    scrape_interval: 30s

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # Agents Supervisor
  - job_name: 'agents-supervisor'
    static_configs:
      - targets: ['agents-supervisor:8001']
    metrics_path: /metrics
    scrape_interval: 15s

  # Redis Exporter (если есть)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Blackbox Exporter для проверки endpoints
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://frontend:3000
          - http://backend:8000/docs
          - http://backend:8000/healthz/readiness
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  # OTEL Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']
    scrape_interval: 30s

  # Qdrant metrics (если поддерживается)
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    metrics_path: /metrics
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
