#!/usr/bin/env bash
set -euo pipefail

DRY_RUN=1
MANIFESTS_REPO="${1:-../predator-manifests}"
BRANCH_NAME="auto/bump-$(date +%s)"
IMAGE_TAG="${IMAGE_TAG:-auto-$(date +%s)}"

usage() {
  cat <<EOF
Usage: $0 [manifests-repo-path] [--execute]

By default this script runs in dry-run mode and prints the git commands it would run.
To actually push and open a PR, pass --execute as second arg and have gh CLI authenticated.
EOF
}

if [ "${2:-}" = "--execute" ]; then
  DRY_RUN=0
fi

if [ ! -d "$MANIFESTS_REPO" ]; then
  echo "manifests repo not found: $MANIFESTS_REPO" >&2; exit 2
fi

pushd "$MANIFESTS_REPO" >/dev/null
echo "[auto_bump] repo: $MANIFESTS_REPO, branch: $BRANCH_NAME, image_tag: $IMAGE_TAG"
if [ "$DRY_RUN" = "1" ]; then
  echo "DRY-RUN: would create branch, update values, commit, push and open PR"
  echo "Commands (dry-run):"
  echo "git checkout -b $BRANCH_NAME"
  echo "yq -i '.image.tag = \"$IMAGE_TAG\"' charts/predator/values.yaml"
  echo "git add charts/predator/values.yaml && git commit -m 'auto: bump image $IMAGE_TAG' -S"
  echo "git push origin $BRANCH_NAME"
  echo "gh pr create --base main --head $BRANCH_NAME --title 'auto: bump to $IMAGE_TAG' --body 'Autogenerated bump'"
  popd >/dev/null
  exit 0
fi

git checkout -b "$BRANCH_NAME"
yq -i ".image.tag = \"$IMAGE_TAG\"" charts/predator/values.yaml || true
git add charts/predator/values.yaml
git commit -S -m "auto: bump image $IMAGE_TAG" || true
git push origin "$BRANCH_NAME"

if command -v gh >/dev/null 2>&1; then
  gh pr create --base main --head "$BRANCH_NAME" --title "auto: bump to $IMAGE_TAG" --body "Autogenerated bump"
else
  echo "gh cli not found; pushed branch $BRANCH_NAME - create PR manually" >&2
fi

popd >/dev/null
echo "[auto_bump] done"
