apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-build
spec:
  params:
    - name: IMAGE
      type: string
    - name: CONTEXT
      type: string
      default: "."
    - name: DOCKERFILE
      type: string
      default: "Dockerfile"
  workspaces:
    - name: source
  steps:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      script: |
        /kaniko/executor --context $(workspaces.source.path)/$(params.CONTEXT) --dockerfile $(workspaces.source.path)/$(params.DOCKERFILE) --destination=$(params.IMAGE) --verbosity=info
