apiVersion: v1
kind: Service
metadata:
  name: predator-api
  labels:
    app: predator-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"
spec:
  selector:
    app: predator-api
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: predator-api-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
  - hosts:
    - api.predator-analytics.com
    secretName: predator-api-tls
  rules:
  - host: api.predator-analytics.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: predator-api
            port:
              number: 8000
