global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'predator11-alerts@your-domain.com'
  smtp_auth_username: ''
  smtp_auth_password: ''

# Правила маршрутизації алертів
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'
    - match_re:
        service: '^(database|redis|opensearch)$'
      receiver: 'infrastructure-alerts'

# Приймачі сповіщень
receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://backend:8000/api/alerts/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://backend:8000/api/alerts/critical'
        send_resolved: true
    # Додати Slack/Email конфігурацію для продакшну
    # slack_configs:
    #   - api_url: 'YOUR_SLACK_WEBHOOK_URL'
    #     channel: '#predator11-alerts'
    #     title: 'CRITICAL: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  - name: 'warning-alerts'
    webhook_configs:
      - url: 'http://backend:8000/api/alerts/warning'
        send_resolved: true

  - name: 'infrastructure-alerts'
    webhook_configs:
      - url: 'http://backend:8000/api/alerts/infrastructure'
        send_resolved: true

# Пригнічення повторюваних алертів
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
