global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'your-email@gmail.com'
  smtp_auth_username: 'your-email@gmail.com'
  smtp_auth_password: 'your-app-password'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email'
  routes:
  - match:
      severity: 'critical'
    receiver: 'email-critical'
    repeat_interval: 30m
  - match_re:
      service: '^(foo1|foo2|baz)$'
    receiver: 'email-foo'

receivers:
- name: 'email'
  email_configs:
  - to: 'alerts@example.com'
    send_resolved: true

- name: 'email-critical'
  email_configs:
  - to: 'critical-alerts@example.com'
    send_resolved: true

- name: 'email-foo'
  email_configs:
  - to: 'foo-alerts@example.com'
    send_resolved: true

templates:
- '/etc/alertmanager/template/*.tmpl'
