apiVersion: v1
kind: ServiceAccount
metadata:
  name: ops-bot
  namespace: predator-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ops-bot-role
  namespace: predator-dev
rules:
- apiGroups: ["", "apps", "argoproj.io", "rollouts.argoproj.io", "autoscaling"]
  resources: ["pods","deployments","services","applications","rollouts","horizontalpodautoscalers"]
  verbs: ["get","list","watch","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ops-bot-rb
  namespace: predator-dev
subjects:
- kind: ServiceAccount
  name: ops-bot
roleRef:
  kind: Role
  name: ops-bot-role
  apiGroup: rbac.authorization.k8s.io
