"""Initial migration.

Revision ID: initial
Revises: 
Create Date: 2023-10-01 00:00:00.000000

"""
from alembic import op  # noqa: F401 - Placeholder for future
                       # migration commands
import sqlalchemy as sa  # noqa: F401 - Placeholder for future
                         # migration commands


# revision identifiers, used by Alembic.
revision = 'initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 