apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-scan
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: git-url
      type: string
    - name: revision
      type: string
      default: "main"
    - name: image
      type: string
    - name: manifests-repo
      type: string
    - name: manifests-branch
      type: string
      default: "main"
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: "$(params.git-url)"
        - name: revision
          value: "$(params.revision)"
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build
      runAfter: [clone]
      taskRef:
        name: kaniko-build
      params:
        - name: IMAGE
          value: "$(params.image)"
        - name: CONTEXT
          value: "."
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: scan
      runAfter: [build]
      taskRef:
        name: trivy-scan
      params:
        - name: IMAGE
          value: "$(params.image)"
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: manifest-update
      runAfter: [scan]
      taskRef:
        name: manifest-update
      params:
        - name: manifests-repo
          value: "$(params.manifests-repo)"
        - name: image
          value: "$(params.image)"
        - name: revision
          value: "$(params.manifests-branch)"
    - name: create-pr
      runAfter: [manifest-update]
      taskRef:
        name: create-manifests-pr
      params:
        - name: manifests-repo
          value: "$(params.manifests-repo)"
        - name: branch
          value: "$(params.manifests-branch)"
        - name: image
          value: "$(params.image)"
        - name: auto-merge
          value: "1"
      workspaces:
        - name: source
          workspace: shared-workspace
