server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          source: attrs
          expressions:
            tag:
      - regex:
          source: tag
          expression: '^(?P<container_name>(?:[^|]*))'
      - timestamp:
          source: time
          format: RFC3339Nano
      - labels:
          stream:
          container_name:
      - output:
          source: output

  # Specific scraping for Predator11 services
  - job_name: predator11-backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: predator11-backend
          __path__: /var/lib/docker/containers/*predator11*backend*/*-json.log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          source: attrs
          expressions:
            tag:
      - regex:
          source: tag
          expression: '^(?P<container_name>(?:[^|]*))'
      - timestamp:
          source: time
          format: RFC3339Nano
      - labels:
          stream:
          container_name:
      - output:
          source: output

  - job_name: predator11-agents
    static_configs:
      - targets:
          - localhost
        labels:
          job: predator11-agents
          __path__: /var/lib/docker/containers/*agents*/*-json.log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          source: attrs
          expressions:
            tag:
      - regex:
          source: tag
          expression: '^(?P<container_name>(?:[^|]*))'
      - timestamp:
          source: time
          format: RFC3339Nano
      - labels:
          stream:
          container_name:
      - match:
          selector: '{job="predator11-agents"}'
          stages:
            - regex:
                source: output
                expression: '(?P<level>DEBUG|INFO|WARNING|ERROR|CRITICAL)'
            - labels:
                level:
      - output:
          source: output
