global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi:8000']
    metrics_path: '/metrics'
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/metrics'
  - job_name: 'celery'
    static_configs:
      - targets: ['celery:5555']
    metrics_path: '/metrics'
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
    metrics_path: '/metrics'
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
    metrics_path: '/metrics' 