apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: prom-http-200-check
spec:
  metrics:
    - name: http-200-check
      interval: 15s
      count: 3
      successCondition: result > 0
      provider:
        prometheus:
          address: http://prometheus:9090
          query: |
            sum(rate(http_requests_total{job="predator-backend",status="200"}[1m]))
