name: Auto Approve & Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  auto_approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  wait_checks:
    runs-on: ubuntu-latest
    needs: auto_approve
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Wait for required checks to pass
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20
          allowed-conclusions: success

  auto_merge:
    needs: wait_checks
    runs-on: ubuntu-latest
    steps:
      - name: Enable automerge (squash)
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
